# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('upcoming', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
