# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('rps', '0004_throw'), ('rps', '0005_throw_human_victory'), ('rps', '0006_throw_game')]

    dependencies = [
        ('rps', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_throw', models.IntegerField()),
                ('human_throw', models.IntegerField()),
                ('human_victory', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.Game')),
            ],
        ),
    ]
