# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Throw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_throw', models.IntegerField()),
                ('human_throw', models.IntegerField()),
            ],
        ),
    ]
