# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rps', '0004_throw_squashed_0006_throw_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throw',
            name='human_victory',
        ),
        migrations.AddField(
            model_name='throw',
            name='game_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='throw',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rps.Game'),
        ),
    ]
